@Harjoitus2_HostAddress = https://localhost:7256

POST {{Harjoitus2_HostAddress}}/quests
Content-Type: application/json
{
    "Name":"Tuhoa rotat",
    "Description":"Tapa 3 rottaa ja tuo nahat minulle",
    "Reward":50
}

###

POST {{Harjoitus2_HostAddress}}/quests
Content-Type: application/json
{
    "Name":"Etsi Viljo",
    "Description":"Onkos Viljoo näkyny?",
    "Reward":100
}

###

GET {{Harjoitus2_HostAddress}}/quests

###

GET {{Harjoitus2_HostAddress}}/quests/1

###

GET {{Harjoitus2_HostAddress}}/quests/2

###

